<?php

$cities = [
    "Almería",
    "Algeciras",
    "Arcos de la Frontera",
    "Cádiz",
    "Chiclana de la Frontera",
    "El Puerto de Santa María",
    "Jerez de la Frontera",
    "La Línea",
    "Puerto Real",
    "San Fernando",
    "Sanlúcar de Barrameda",
    "Bujalance",
    "Cabra",
    "Córdoba",
    "Lucena",
    "Montilla",
    "Peñarroya-Pueblonuevo",
    "Priego de Córdoba",
    "Puente-Genil",
    "Andújar",
    "Baza",
    "Granada",
    "Guadix",
    "Motril",
    "Huelva",
    "Jaén",
    "Linares",
    "Martos",
    "Úbeda",
    "Antequera",
    "Coín",
    "Málaga",
    "Melilla",
    "Ronda",
    "Alcalá de Guadaira",
    "Carmona",
    "Dos Hermanas",
    "Ecija",
    "Lebrija",
    "Lora del Río",
    "Marchena",
    "Morón de la Frontera",
    "Osuna",
    "Sevilla",
    "Utrera",
    "Huesca",
    "Jaca",
    "Teruel",
    "Zaragoza",
    "Avilés",
    "Cabañaquinta",
    "Cangas de Narcea",
    "Covadonga",
    "Gijón",
    "Luarca",
    "Mieres",
    "Oviedo",
    "Pola de Siero",
    "San Martín del Rey Aurelio",
    "Tineo",
    "Villaviciosa",
    "Palma",
    "Maó",
    "Vitoria-Gasteiz",
    "Donostia–San Sebastián",
    "Eibar",
    "Irun",
    "Barakaldo",
    "Bilbao",
    "Getxo",
    "Guernica",
    "Portugalete",
    "Santurtzi",
    "Sestao",
    "Arucas",
    "Las Palmas",
    "Telde",
    "La Orotava",
    "Santa Cruz de Tenerife",
    "Santander",
    "Torrelavega",
    "Albacete",
    "Hellín",
    "Villarrobledo",
    "Alcázar de San Juan",
    "Almadén",
    "Ciudad Real",
    "Puertollano",
    "Tomelloso",
    "Valdepeñas",
    "Cuenca",
    "Guadalajara",
    "Talavera de la Reina",
    "Toledo",
    "Ávila",
    "Burgos",
    "Miranda de Ebro",
    "Astorga",
    "León",
    "Ponferrada",
    "Palencia",
    "Ciudad Rodrigo",
    "Salamanca",
    "San Ildefonso",
    "Segovia",
    "Soria",
    "Simancas",
    "Valladolid",
    "Toro",
    "Zamora",
    "Badalona",
    "Barcelona",
    "Cornellà",
    "Granollers",
    "L’Hospitalet de Llobregat",
    "Manresa",
    "Mataró",
    "Reus",
    "Sabadell",
    "Santa Coloma de Gramenet",
    "Terrassa",
    "Vic",
    "Vilanova i la Geltrú",
    "Girona",
    "Llívia",
    "Lleida",
    "Tarragona",
    "Tortosa",
    "Almendralejo",
    "Badajoz",
    "Don Benito",
    "Mérida",
    "Villanueva de la Serena",
    "Alcántara",
    "Cáceres",
    "Guadalupe",
    "Plasencia",
    "Trujillo",
    "A Coruña",
    "Carballo",
    "Ferrol",
    "Ortigueira",
    "Ribeira",
    "Santiago de Compostela",
    "Lugo",
    "Mondoñedo",
    "Monforte de Lemos",
    "Vilalba",
    "Ourense",
    "Vigo",
    "Vilagarcía de Arousa",
    "Pontevedra",
    "Alcalá de Henares",
    "Aranjuez",
    "El Escorial",
    "Getafe",
    "Madrid",
    "Caravaca",
    "Cartagena",
    "Cieza",
    "Jumilla",
    "Lorca",
    "Murcia",
    "Yecla",
    "Funes",
    "Pamplona",
    "Roncesvalles",
    "Calahorra",
    "Logroño",
    "Alcoy",
    "Alicante",
    "Elche",
    "Elda",
    "Orihuela",
    "Villena",
    "Castellón de la Plana",
    "Villarreal",
    "Alzira",
    "Gandía",
    "Requena",
    "Sagunto",
    "Sueca",
    "Torrent",
    "Valencia"
];

$startText = $_GET["startText"]; 
$searchCities = []; 

function startsWith($string, $startString) { 
    $len = strlen($startString); 
    return (strcasecmp( $startString, substr($string, 0, $len)) == 0); 
} 

foreach ($cities as $city) {
    if (startsWith($city, $startText)) {
        $searchCities[] = $city; 
    }
}

echo json_encode($searchCities);  